# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a407a7c760546891fc2a3aa31ea4332ddf6f5842839ecae16fde3e6e833eef06f30f3689960c9f9493db49885a518903b5346f3637f94cf490573d04c900ff

test:
  secret_key_base: ba3ea26480b93cf37f4c1edf86f8ef17213deb35d0a394d5f08ed3eea05508a696707d07ca5ec8c7f12deaf4fc778bdcdbcf09b12bd4bace382bf8d4ec5af361

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
